export { default as Home } from './Home'
export { default as Movies } from './Movies'
export { default as Series } from './Series'
export { default as DetailMovies } from './DetailMovies'
export { default as DetailSeries } from './DetailSeries'
export { default as Favorites } from './Favorites'